matrix:
    language: node_js
#    before_install:
#  - npm install
    script:
      - npm run css
  include:
    language: ruby
    before_install:
      - gem install bundler
    script:
      - bundle exec rake test
