matrix:
  include:

    language: node_js
    install:
      - npm install
    script:
      - npm run css

#    language: ruby
#    before_install:
#      - gem install bundler
#    script:
#      - bundle exec rake test
