matrix:
  include:

    language: node_js
    node_js:
      - "10.3.0"
    install:
      - npm install

    language: ruby
    #rvm: "2.5.1"
    before_install:
      - gem install bundler
    script:
      - npm run css
      - bundle install
      - bundle exec rake test
