matrix:
  include:

#    language: node_js
#    node_js:
#      - "10.3.0"
#    install:
#      - npm install
#    script:
#      - npm run css

    language: ruby
    ruby: "2.5.1"
    before_install:
      - gem install bundler
    script:
      - bundle exec rake test
